module.exports = {
	HVS2000: {
		COMMANDS: {
			GET_INPUTS: "GET.SIGNALS_INFO",
			GET_STATE: "GET.PNL_ALLDATA",
			//REBOOT: "CMD.020103", // Not supported on HVS2000
			// event: 2-digit hex for the selected event
			//RECALL_EVENT: "CMD.030502{event}",
			// me: which me to transition
			TRANS_ME_AUTO: "SET.M{me}BG_TRANSITION:AUTO",
			// me: which me to transition
			TRANS_ME_CUT: "SET.M{me}BG_TRANSITION:CUT",
			// me: which me owns the key
			// key: which key to transition
			TRANS_KEY_AUTO: "SET.M{me}K{key}_TRANSITION:AUTO",
			// me: which me owns the key
			// key: which key to transition
			TRANS_KEY_CUT: "SET.M{me}K{key}_TRANSITION:CUT",
			// key: which flex key to transition
			TRANS_FLEX_KEY_AUTO: "SET.FLX{key}_TRANSITION:AUTO",
			// key: which flex key to transition
			TRANS_FLEX_KEY_CUT: "SET.FLX{key}_TRANSITION:CUT",
			// me: which me to set
			// layer: which layer to set
			// source: id of the selected source
			XPT_ME: "SET.M{me}BG_XPT_{layer}:{source}",
			// aux: which aux to set
			// source: id of the selected source
			XPT_AUX: "SET.AUX{aux}_XPT:{source}",
			// mel: which mel to transition
			TRANS_MEL_AUTO: "SET.MEL{mel}_TRANSITION:AUTO",
			// mel: which mel to transition
			TRANS_MEL_CUT: "SET.MEL{mel}_TRANSITION:CUT",
			// mel: which mel to set
			// layer: which layer to set
			// source: id of the selected source
			XPT_MEL: "SET.MEL{mel}BG_XPT_{layer}:{source}",
		},
		ME_LAYERS: { A: "PGM", B: "PST" },
		AUXES: [
			{ id: 1, label: "Aux 1" },
			{ id: 2, label: "Aux 2" },
			{ id: 3, label: "Aux 3" },
			{ id: 4, label: "Aux 4" },
			{ id: 5, label: "Aux 5" },
			{ id: 6, label: "Aux 6" },
			{ id: 7, label: "Aux 7" },
			{ id: 8, label: "Aux 8" },
			{ id: 9, label: "Aux 9" },
			{ id: 10, label: "Aux 10" },
			{ id: 11, label: "Aux 11" },
			{ id: 12, label: "Aux 12" },
			{ id: 13, label: "Aux 13" },
			{ id: 14, label: "Aux 14" },
			{ id: 15, label: "Aux 15" },
			{ id: 16, label: "Aux 16" },
			{ id: 17, label: "Aux 17" },
			{ id: 18, label: "Aux 18" },
		],
		VARIABLES: [
			{ label: 'Last global event to be recalled', name: 'global_event_recall' },
			{ label: 'Last ME1 event to be recalled', name: 'me_1_event_recall' },
			{ label: 'Last ME2 event to be recalled', name: 'me_2_event_recall' },
			{ label: 'Last ME3 event to be recalled', name: 'me_3_event_recall' },
			{ label: 'ME1 KEY 1 on/off', name: 'me_1_key_1' },
			{ label: 'ME1 KEY 2 on/off', name: 'me_1_key_2' },
			{ label: 'ME1 KEY 3 on/off', name: 'me_1_key_3' },
			{ label: 'ME1 KEY 4 on/off', name: 'me_1_key_4' },
			{ label: 'ME2 KEY 1 on/off', name: 'me_2_key_1' },
			{ label: 'ME2 KEY 2 on/off', name: 'me_2_key_2' },
			{ label: 'ME2 KEY 3 on/off', name: 'me_2_key_3' },
			{ label: 'ME2 KEY 4 on/off', name: 'me_2_key_4' },
			{ label: 'ME3 KEY 1 on/off', name: 'me_3_key_1' },
			{ label: 'ME3 KEY 2 on/off', name: 'me_3_key_2' },
			{ label: 'ME3 KEY 3 on/off', name: 'me_3_key_3' },
			{ label: 'ME3 KEY 4 on/off', name: 'me_3_key_4' },
			{ label: 'FLEX KEY 1 on/off', name: 'flex_key_1' },
			{ label: 'FLEX KEY 2 on/off', name: 'flex_key_2' },
			{ label: 'FLEX KEY 3 on/off', name: 'flex_key_3' },
			{ label: 'FLEX KEY 4 on/off', name: 'flex_key_4' },
			{ name: "short_black", label: "Short name of Black", default: "BLK", no: 0 },
			{ name: "short_1", label: "Short name of input 1", default: "In 1", no: 1 },
			{ name: "short_2", label: "Short name of input 2", default: "In 2", no: 2 },
			{ name: "short_3", label: "Short name of input 3", default: "In 3", no: 3 },
			{ name: "short_4", label: "Short name of input 4", default: "In 4", no: 4 },
			{ name: "short_5", label: "Short name of input 5", default: "In 5", no: 5 },
			{ name: "short_6", label: "Short name of input 6", default: "In 6", no: 6 },
			{ name: "short_7", label: "Short name of input 7", default: "In 7", no: 7 },
			{ name: "short_8", label: "Short name of input 8", default: "In 8", no: 8 },
			{ name: "short_9", label: "Short name of input 9", default: "In 9", no: 9 },
			{ name: "short_10", label: "Short name of input 10", default: "In10", no: 10 },
			{ name: "short_11", label: "Short name of input 11", default: "In11", no: 11 },
			{ name: "short_12", label: "Short name of input 12", default: "In12", no: 12 },
			{ name: "short_13", label: "Short name of input 13", default: "In13", no: 13 },
			{ name: "short_14", label: "Short name of input 14", default: "In14", no: 14 },
			{ name: "short_15", label: "Short name of input 15", default: "In15", no: 15 },
			{ name: "short_16", label: "Short name of input 16", default: "In16", no: 16 },
			{ name: "short_17", label: "Short name of input 17", default: "In17", no: 17 },
			{ name: "short_18", label: "Short name of input 18", default: "In18", no: 18 },
			{ name: "short_19", label: "Short name of input 19", default: "In19", no: 19 },
			{ name: "short_20", label: "Short name of input 20", default: "In20", no: 20 },
			{ name: "short_21", label: "Short name of input 21", default: "In21", no: 21 },
			{ name: "short_22", label: "Short name of input 22", default: "In22", no: 22 },
			{ name: "short_23", label: "Short name of input 23", default: "In23", no: 23 },
			{ name: "short_24", label: "Short name of input 24", default: "In24", no: 24 },
			{ name: "short_25", label: "Short name of input 25", default: "In25", no: 25 },
			{ name: "short_26", label: "Short name of input 26", default: "In26", no: 26 },
			{ name: "short_27", label: "Short name of input 27", default: "In27", no: 27 },
			{ name: "short_28", label: "Short name of input 28", default: "In28", no: 28 },
			{ name: "short_29", label: "Short name of input 29", default: "In29", no: 29 },
			{ name: "short_30", label: "Short name of input 30", default: "In30", no: 30 },
			{ name: "short_31", label: "Short name of input 31", default: "In31", no: 31 },
			{ name: "short_32", label: "Short name of input 32", default: "In32", no: 32 },
			{ name: "short_33", label: "Short name of input 33", default: "In33", no: 33 },
			{ name: "short_34", label: "Short name of input 34", default: "In34", no: 34 },
			{ name: "short_35", label: "Short name of input 35", default: "In35", no: 35 },
			{ name: "short_36", label: "Short name of input 36", default: "In36", no: 36 },
			{ name: "short_37", label: "Short name of input 37", default: "In37", no: 37 },
			{ name: "short_38", label: "Short name of input 38", default: "In38", no: 38 },
			{ name: "short_39", label: "Short name of input 39", default: "In39", no: 39 },
			{ name: "short_40", label: "Short name of input 40", default: "In40", no: 40 },
			{ name: "short_41", label: "Short name of input 41", default: "In41", no: 41 },
			{ name: "short_42", label: "Short name of input 42", default: "In42", no: 42 },
			{ name: "short_43", label: "Short name of input 43", default: "In43", no: 43 },
			{ name: "short_44", label: "Short name of input 44", default: "In44", no: 44 },
			{ name: "short_45", label: "Short name of input 45", default: "In45", no: 45 },
			{ name: "short_46", label: "Short name of input 46", default: "In46", no: 46 },
			{ name: "short_47", label: "Short name of input 47", default: "In47", no: 47 },
			{ name: "short_48", label: "Short name of input 48", default: "In48", no: 48 },
			{ name: "short_still1", label: "Short name of Still 1", default: "STL1", no: 49 },
			{ name: "short_still2", label: "Short name of Still 2", default: "STL2", no: 50 },
			{ name: "short_still3", label: "Short name of Still 3", default: "STL3", no: 51 },
			{ name: "short_still4", label: "Short name of Still 4", default: "STL4", no: 52 },
			{ name: "short_still5", label: "Short name of Still 5", default: "STL5", no: 53 },
			{ name: "short_still6", label: "Short name of Still 6", default: "STL6", no: 54 },
			{ name: "short_bars", label: "Short name of Color Bars", default: "BARS", no: 61 },
			{ name: "short_white", label: "Short name of White", default: "WHT", no: 62 },
			{ name: "short_matte1", label: "Short name of Matte 1", default: "MAT1", no: 63 },
			{ name: "short_matte2", label: "Short name of Matte 2", default: "MAT2", no: 64 },
			{ name: "short_grandmatte", label: "Short name of Grand Matte", default: "GMAT", no: 65 },
			{ name: "short_me1", label: "Short name of ME1", default: "ME1", no: 72 },
			{ name: "short_me1out1", label: "Short name of ME1 Out 1", default: "ME1-1", no: 73 },
			{ name: "short_me1out2", label: "Short name of ME1 Out 2", default: "ME1-2", no: 74 },
			{ name: "short_me2", label: "Short name of ME2", default: "ME2", no: 75 },
			{ name: "short_me2out1", label: "Short name of ME2 Out 1", default: "ME2-1", no: 76 },
			{ name: "short_me2out2", label: "Short name of ME2 Out 2", default: "ME2-2", no: 77 },
			{ name: "short_mv1outa", label: "Short name of MV1 Out A", default: "MV1-A", no: 80 },
			{ name: "short_mv2outa", label: "Short name of MV2 Out A", default: "MV2-A", no: 81 },
			{ name: "short_me3", label: "Short name of ME3", default: "ME3", no: 84 },
			{ name: "short_me3out1", label: "Short name of ME3 Out 1", default: "ME3-1", no: 85 },
			{ name: "short_me3out2", label: "Short name of ME3 Out 2", default: "ME3-2", no: 86 },
			{ name: "short_mv3outa", label: "Short name of MV3 Out A", default: "MV3-A", no: 95 },
			{ name: "short_mv4outa", label: "Short name of MV4 Out A", default: "MV4-A", no: 96 },
			{ name: "short_me1out3", label: "Short name of ME1 Out 3", default: "ME1-3", no: 105 },
			{ name: "short_me2out3", label: "Short name of ME2 Out 3", default: "ME2-3", no: 106 },
			{ name: "short_me3out3", label: "Short name of ME3 Out 3", default: "ME3-3", no: 107 },
			{ name: "short_chromakey1fill", label: "Short name of Chroma Key 1 Fill", default: "CK1F", no: 108 },
			{ name: "short_chromakey1key", label: "Short name of Chroma Key 1 Key", default: "CK1K", no: 109 },
			{ name: "short_chromakey2fill", label: "Short name of Chroma Key 2 Fill", default: "CK2F", no: 110 },
			{ name: "short_chromakey2key", label: "Short name of Chroma Key 2 Key", default: "CK2K", no: 111 },
			{ name: "short_chromakey3fill", label: "Short name of Chroma Key 3 Fill", default: "CK3F", no: 112 },
			{ name: "short_chromakey3key", label: "Short name of Chroma Key 3 Key", default: "CK3K", no: 113 },
			{ name: "short_chromakey4fill", label: "Short name of Chroma Key 4 Fill", default: "CK4F", no: 114 },
			{ name: "short_chromakey4key", label: "Short name of Chroma Key 4 Key", default: "CK4K", no: 115 },
			{ name: "short_chromakey5fill", label: "Short name of Chroma Key 5 Fill", default: "CK5F", no: 116 },
			{ name: "short_chromakey5key", label: "Short name of Chroma Key 5 Key", default: "CK5K", no: 117 },
			{ name: "short_chromakey6fill", label: "Short name of Chroma Key 6 Fill", default: "CK6F", no: 118 },
			{ name: "short_chromakey6key", label: "Short name of Chroma Key 6 Key", default: "CK6K", no: 119 },
			{ name: "short_chromakey7fill", label: "Short name of Chroma Key 7 Fill", default: "CK7F", no: 120 },
			{ name: "short_chromakey7key", label: "Short name of Chroma Key 7 Key", default: "CK7K", no: 121 },
			{ name: "short_chromakey8fill", label: "Short name of Chroma Key 8 Fill", default: "CK8F", no: 122 },
			{ name: "short_chromakey8key", label: "Short name of Chroma Key 8 Key", default: "CK8K", no: 123 },
			{ name: "short_effect1", label: "Short name of Effect 1", default: "EFF1", no: 124 },
			{ name: "short_effect2", label: "Short name of Effect 2", default: "EFF2", no: 125 },
			{ name: "short_effect3", label: "Short name of Effect 3", default: "EFF3", no: 126 },
			{ name: "short_effect4", label: "Short name of Effect 4", default: "EFF4", no: 127 },
			{ name: "short_colorcorrect1", label: "Short name of Color Correct 1", default: "CC1", no: 130 },
			{ name: "short_colorcorrect2", label: "Short name of Color Correct 2", default: "CC2", no: 131 },
			{ name: "short_colorcorrect3", label: "Short name of Color Correct 3", default: "CC3", no: 132 },
			{ name: "short_colorcorrect4", label: "Short name of Color Correct 4", default: "CC4", no: 133 },
			{ name: "short_colorcorrect5", label: "Short name of Color Correct 5", default: "CC5", no: 134 },
			{ name: "short_colorcorrect6", label: "Short name of Color Correct 6", default: "CC6", no: 135 },
			{ name: "short_colorcorrect7", label: "Short name of Color Correct 7", default: "CC7", no: 136 },
			{ name: "short_colorcorrect8", label: "Short name of Color Correct 8", default: "CC8", no: 137 },
			{ name: "short_aux1", label: "Short name of Aux 1", default: "Aux1", no: 139 },
			{ name: "short_aux2", label: "Short name of Aux 2", default: "Aux2", no: 140 },
			{ name: "short_aux3", label: "Short name of Aux 3", default: "Aux3", no: 141 },
			{ name: "short_aux4", label: "Short name of Aux 4", default: "Aux4", no: 142 },
			{ name: "short_aux5", label: "Short name of Aux 5", default: "Aux5", no: 143 },
			{ name: "short_aux6", label: "Short name of Aux 6", default: "Aux6", no: 144 },
			{ name: "short_aux7", label: "Short name of Aux 7", default: "Aux7", no: 145 },
			{ name: "short_aux8", label: "Short name of Aux 8", default: "Aux8", no: 146 },
			{ name: "short_aux9", label: "Short name of Aux 9", default: "Aux9", no: 147 },
			{ name: "short_aux10", label: "Short name of Aux 10", default: "Aux10", no: 148 },
			{ name: "short_aux11", label: "Short name of Aux 11", default: "Aux11", no: 149 },
			{ name: "short_aux12", label: "Short name of Aux 12", default: "Aux12", no: 150 },
			{ name: "short_aux13", label: "Short name of Aux 13", default: "Aux13", no: 151 },
			{ name: "short_aux14", label: "Short name of Aux 14", default: "Aux14", no: 152 },
			{ name: "short_aux15", label: "Short name of Aux 15", default: "Aux15", no: 153 },
			{ name: "short_aux16", label: "Short name of Aux 16", default: "Aux16", no: 154 },
			{ name: "short_aux17", label: "Short name of Aux 17", default: "Aux17", no: 155 },
			{ name: "short_aux18", label: "Short name of Aux 18", default: "Aux18", no: 156 },
			{ name: "short_melite1pgm", label: "Short name of MELite 1 PGM", default: "MEL1 PGM", no: 157 },
			{ name: "short_melite2pgm", label: "Short name of MELite 2 PGM", default: "MEL2 PGM", no: 158 },
			{ name: "short_melite3pgm", label: "Short name of MELite 3 PGM", default: "MEL3 PGM", no: 159 },
			{ name: "short_melite4pgm", label: "Short name of MELite 4 PGM", default: "MEL4 PGM", no: 160 },
			{ name: "short_melite5pgm", label: "Short name of MELite 5 PGM", default: "MEL5 PGM", no: 161 },
			{ name: "short_melite6pgm", label: "Short name of MELite 6 PGM", default: "MEL6 PGM", no: 162 },
			{ name: "short_melite1pvw", label: "Short name of MELite 1 PVW", default: "MEL1 PVW", no: 163 },
			{ name: "short_melite2pvw", label: "Short name of MELite 2 PVW", default: "MEL2 PVW", no: 164 },
			{ name: "short_melite3pvw", label: "Short name of MELite 3 PVW", default: "MEL3 PVW", no: 165 },
			{ name: "short_melite4pvw", label: "Short name of MELite 4 PVW", default: "MEL4 PVW", no: 166 },
			{ name: "short_melite5pvw", label: "Short name of MELite 5 PVW", default: "MEL5 PVW", no: 167 },
			{ name: "short_melite6pvw", label: "Short name of MELite 6 PVW", default: "MEL6 PVW", no: 168 },
			{ name: "short_still1key", label: "Short name of Still 1 Key", default: "STK1", no: 169 },
			{ name: "short_still2key", label: "Short name of Still 2 Key", default: "STK2", no: 170 },
			{ name: "short_still3key", label: "Short name of Still 3 Key", default: "STK3", no: 171 },
			{ name: "short_still4key", label: "Short name of Still 4 Key", default: "STK4", no: 172 },
			{ name: "short_still5key", label: "Short name of Still 5 Key", default: "STK5", no: 173 },
			{ name: "short_still6key", label: "Short name of Still 6 Key", default: "STK6", no: 174 },
			{ name: "short_mv1outb", label: "Short name of MV1 Out B", default: "MV1-B", no: 175 },
			{ name: "short_mv2outb", label: "Short name of MV2 Out B", default: "MV2-B", no: 176 },
			{ name: "short_mv3outb", label: "Short name of MV3 Out B", default: "MV3-B", no: 177 },
			{ name: "short_mv4outb", label: "Short name of MV4 Out B", default: "MV4-B", no: 178 }
		],
		MES: [
			{ id: 1, label: "ME 1" },
			{ id: 2, label: "ME 2" },
			{ id: 3, label: "ME 3" },
		],
		MELS: [
			{ id: 1, label: "MELite 1" },
			{ id: 2, label: "MELite 2" },
			{ id: 3, label: "MELite 3" },
			{ id: 4, label: "MELite 4" },
			{ id: 5, label: "MELite 5" },
			{ id: 6, label: "MELite 6" },
		],
		KEYS: [
			{ id: "1,1", label: "ME1 Key1" },
			{ id: "1,2", label: "ME1 Key2" },
			{ id: "1,3", label: "ME1 Key3" },
			{ id: "1,4", label: "ME1 Key4" },
			{ id: "2,1", label: "ME2 Key1" },
			{ id: "2,2", label: "ME2 Key2" },
			{ id: "2,3", label: "ME2 Key3" },
			{ id: "2,4", label: "ME2 Key4" },
			{ id: "3,1", label: "ME3 Key1" },
			{ id: "3,2", label: "ME3 Key2" },
			{ id: "3,3", label: "ME3 Key3" },
			{ id: "3,4", label: "ME3 Key4" },
		],
		FLEX_KEYS: [
			{ id: 1, label: "Flex Key1" },
			{ id: 2, label: "Flex Key2" },
			{ id: 3, label: "Flex Key3" },
			{ id: 4, label: "Flex Key4" },
		],
		get SOURCES_ME() {
			let sources = [
				// Built-in Inputs
				{ id: 1, label: "Source 1" },
				{ id: 2, label: "Source 2" },
				{ id: 3, label: "Source 3" },
				{ id: 4, label: "Source 4" },
				{ id: 5, label: "Source 5" },
				{ id: 6, label: "Source 6" },
				{ id: 7, label: "Source 7" },
				{ id: 8, label: "Source 8" },
				{ id: 9, label: "Source 9" },
				{ id: 10, label: "Source 10" },
				{ id: 11, label: "Source 11" },
				{ id: 12, label: "Source 12" },
				{ id: 13, label: "Source 13" },
				{ id: 14, label: "Source 14" },
				{ id: 15, label: "Source 15" },
				{ id: 16, label: "Source 16" },
				{ id: 17, label: "Source 17" },
				{ id: 18, label: "Source 18" },
				{ id: 19, label: "Source 19" },
				{ id: 20, label: "Source 20" },
				{ id: 21, label: "Source 21" },
				{ id: 22, label: "Source 22" },
				{ id: 23, label: "Source 23" },
				{ id: 24, label: "Source 24" },
				// Optional expansion card inputs
				{ id: 25, label: "Source 25" },
				{ id: 26, label: "Source 26" },
				{ id: 27, label: "Source 27" },
				{ id: 28, label: "Source 28" },
				{ id: 29, label: "Source 29" },
				{ id: 30, label: "Source 30" },
				{ id: 31, label: "Source 31" },
				{ id: 32, label: "Source 32" },
				{ id: 33, label: "Source 33" },
				{ id: 34, label: "Source 34" },
				{ id: 35, label: "Source 35" },
				{ id: 36, label: "Source 36" },
				{ id: 37, label: "Source 37" },
				{ id: 38, label: "Source 38" },
				{ id: 39, label: "Source 39" },
				{ id: 40, label: "Source 40" },
				{ id: 41, label: "Source 41" },
				{ id: 42, label: "Source 42" },
				{ id: 43, label: "Source 43" },
				{ id: 44, label: "Source 44" },
				{ id: 45, label: "Source 45" },
				{ id: 46, label: "Source 46" },
				{ id: 47, label: "Source 47" },
				{ id: 48, label: "Source 48" },
			];
			let system = [
				// System inputs
				{ id: 0, label: "Black" },
				{ id: 49, label: "Still 1" },
				{ id: 50, label: "Still 2" },
				{ id: 51, label: "Still 3" },
				{ id: 52, label: "Still 4" },
				{ id: 53, label: "Still 5" },
				{ id: 54, label: "Still 6" },
				{ id: 61, label: "Color Bars" },
				{ id: 62, label: "White" },
				{ id: 63, label: "Matte 1" },
				{ id: 64, label: "Matte 2" },
				{ id: 65, label: "Grand Matte" },

				{ id: 72, label: "ME1" },
				{ id: 73, label: "ME1 Out 1" },
				{ id: 74, label: "ME1 Out 2" },
				{ id: 75, label: "ME2" },
				{ id: 76, label: "ME2 Out 1" },
				{ id: 77, label: "ME2 Out 2" },

				{ id: 80, label: "MV1 Out A" },
				{ id: 81, label: "MV2 Out A" },

				{ id: 84, label: "ME3" },
				{ id: 85, label: "ME3 Out 1" },
				{ id: 86, label: "ME3 Out 2" },

				{ id: 95, label: "MV3 Out A" },
				{ id: 96, label: "MV4 Out A" },

				{ id: 105, label: "ME1 Out 3" },
				{ id: 106, label: "ME2 Out 3" },
				{ id: 107, label: "ME3 Out 3" },
				{ id: 108, label: "Chroma Key 1 Fill" },
				{ id: 109, label: "Chroma Key 1 Key" },
				{ id: 110, label: "Chroma Key 2 Fill" },
				{ id: 111, label: "Chroma Key 2 Key" },
				{ id: 112, label: "Chroma Key 3 Fill" },
				{ id: 113, label: "Chroma Key 3 Key" },
				{ id: 114, label: "Chroma Key 4 Fill" },
				{ id: 115, label: "Chroma Key 4 Key" },
				{ id: 116, label: "Chroma Key 5 Fill" },
				{ id: 117, label: "Chroma Key 5 Key" },
				{ id: 118, label: "Chroma Key 6 Fill" },
				{ id: 119, label: "Chroma Key 6 Key" },
				{ id: 120, label: "Chroma Key 7 Fill" },
				{ id: 121, label: "Chroma Key 7 Key" },
				{ id: 122, label: "Chroma Key 8 Fill" },
				{ id: 123, label: "Chroma Key 8 Key" },
				{ id: 124, label: "Effect 1" },
				{ id: 125, label: "Effect 2" },
				{ id: 126, label: "Effect 3" },
				{ id: 127, label: "Effect 4" },

				{ id: 130, label: "Color Correct 1" },
				{ id: 131, label: "Color Correct 2" },
				{ id: 132, label: "Color Correct 3" },
				{ id: 133, label: "Color Correct 4" },
				{ id: 134, label: "Color Correct 5" },
				{ id: 135, label: "Color Correct 6" },
				{ id: 136, label: "Color Correct 7" },
				{ id: 137, label: "Color Correct 8" },

				{ id: 139, label: "Aux 1" },
				{ id: 140, label: "Aux 2" },
				{ id: 141, label: "Aux 3" },
				{ id: 142, label: "Aux 4" },
				{ id: 143, label: "Aux 5" },
				{ id: 144, label: "Aux 6" },
				{ id: 145, label: "Aux 7" },
				{ id: 146, label: "Aux 8" },
				{ id: 147, label: "Aux 9" },
				{ id: 148, label: "Aux 10" },
				{ id: 149, label: "Aux 11" },
				{ id: 150, label: "Aux 12" },
				{ id: 151, label: "Aux 13" },
				{ id: 152, label: "Aux 14" },
				{ id: 153, label: "Aux 15" },
				{ id: 154, label: "Aux 16" },
				{ id: 155, label: "Aux 17" },
				{ id: 156, label: "Aux 18" },
				{ id: 157, label: "MELite 1 PGM" },
				{ id: 158, label: "MELite 2 PGM" },
				{ id: 159, label: "MELite 3 PGM" },
				{ id: 160, label: "MELite 4 PGM" },
				{ id: 161, label: "MELite 5 PGM" },
				{ id: 162, label: "MELite 6 PGM" },
				{ id: 163, label: "MELite 1 PVW" },
				{ id: 164, label: "MELite 2 PVW" },
				{ id: 165, label: "MELite 3 PVW" },
				{ id: 166, label: "MELite 4 PVW" },
				{ id: 167, label: "MELite 5 PVW" },
				{ id: 168, label: "MELite 6 PVW" },
				{ id: 169, label: "Still 1 Key" },
				{ id: 170, label: "Still 2 Key" },
				{ id: 171, label: "Still 3 Key" },
				{ id: 172, label: "Still 4 Key" },
				{ id: 173, label: "Still 5 Key" },
				{ id: 174, label: "Still 6 Key" },
				{ id: 175, label: "MV1 Out B" },
				{ id: 176, label: "MV2 Out B" },
				{ id: 177, label: "MV3 Out B" },
				{ id: 178, label: "MV4 Out B" },
			];
			return sources.concat(
				system.sort((a, b) => (a.label > b.label ? 1 : -1))
			);
		},
		get SOURCES_AUX() {
			return this.SOURCES_ME; // HVS2000 Has no Aux-only sources
		},
	},
};
