module.exports = {
	HVS2000: {
		COMMANDS: {
			GET_INPUTS: "GET.SIGNALS_INFO",
			GET_STATE: "GET.PNL_ALLDATA",
			//REBOOT: "CMD.020103", // Not supported on HVS2000
			// event: 2-digit hex for the selected event
			//RECALL_EVENT: "CMD.030502{event}",
			// macroInt: which macro to recall
			RECALL_MACRO: "SET.MACRO_PLAY:{macroInt}=0",
			// me: which me to transition
			TRANS_ME_AUTO: "SET.M{me}BG_TRANSITION:AUTO",
			// me: which me to transition
			TRANS_ME_CUT: "SET.M{me}BG_TRANSITION:CUT",
			// me: which me owns the key
			// key: which key to transition
			TRANS_KEY_AUTO: "SET.M{me}K{key}_TRANSITION:AUTO",
			// me: which me owns the key
			// key: which key to transition
			TRANS_KEY_CUT: "SET.M{me}K{key}_TRANSITION:CUT",
			// key: which flex key to transition
			TRANS_FLEX_KEY_AUTO: "SET.FLX{key}_TRANSITION:AUTO",
			// key: which flex key to transition
			TRANS_FLEX_KEY_CUT: "SET.FLX{key}_TRANSITION:CUT",
			// me: which me to set
			// layer: which layer to set
			// source: id of the selected source
			XPT_ME: "SET.M{me}BG_XPT_{layer}:{source}",
			// aux: which aux to set
			// source: id of the selected source
			XPT_AUX: "SET.AUX{aux}_XPT:{source}",
			// mel: which mel to transition
			TRANS_MEL_AUTO: "SET.MEL{mel}_TRANSITION:AUTO",
			// mel: which mel to transition
			TRANS_MEL_CUT: "SET.MEL{mel}_TRANSITION:CUT",
			// mel: which mel to set
			// layer: which layer to set
			// source: id of the selected source
			XPT_MEL: "SET.MEL{mel}BG_XPT_{layer}:{source}",
		},
		ME_LAYERS: { A: "PGM", B: "PST" },
		AUXES: [
			{ id: 1, label: "Aux 1", sName: "Aux1", no: 139 },
			{ id: 2, label: "Aux 2", sName: "Aux2", no: 140 },
			{ id: 3, label: "Aux 3", sName: "Aux3", no: 141 },
			{ id: 4, label: "Aux 4", sName: "Aux4", no: 142 },
			{ id: 5, label: "Aux 5", sName: "Aux5", no: 143 },
			{ id: 6, label: "Aux 6", sName: "Aux6", no: 144 },
			{ id: 7, label: "Aux 7", sName: "Aux7", no: 145 },
			{ id: 8, label: "Aux 8", sName: "Aux8", no: 146 },
			{ id: 9, label: "Aux 9", sName: "Aux9", no: 147 },
			{ id: 10, label: "Aux 10", sName: "Ax10", no: 148 },
			{ id: 11, label: "Aux 11", sName: "Ax11", no: 149 },
			{ id: 12, label: "Aux 12", sName: "Ax12", no: 150 },
			{ id: 13, label: "Aux 13", sName: "Ax13", no: 151 },
			{ id: 14, label: "Aux 14", sName: "Ax14", no: 152 },
			{ id: 15, label: "Aux 15", sName: "Ax15", no: 153 },
			{ id: 16, label: "Aux 16", sName: "Ax16", no: 154 },
			{ id: 17, label: "Aux 17", sName: "Ax17", no: 155 },
			{ id: 18, label: "Aux 18", sName: "Ax18", no: 156 },
		],
		VARIABLES: [
			{
				name: "Last global event to be recalled",
				variableId: "global_event_recall",
			},
			{
				name: "Last ME1 event to be recalled",
				variableId: "me_1_event_recall",
			},
			{
				name: "Last ME2 event to be recalled",
				variableId: "me_2_event_recall",
			},
			{
				name: "Last ME3 event to be recalled",
				variableId: "me_3_event_recall",
			},
			{ name: "ME1 KEY 1 on/off", variableId: "me_1_key_1" },
			{ name: "ME1 KEY 2 on/off", variableId: "me_1_key_2" },
			{ name: "ME1 KEY 3 on/off", variableId: "me_1_key_3" },
			{ name: "ME1 KEY 4 on/off", variableId: "me_1_key_4" },
			{ name: "ME2 KEY 1 on/off", variableId: "me_2_key_1" },
			{ name: "ME2 KEY 2 on/off", variableId: "me_2_key_2" },
			{ name: "ME2 KEY 3 on/off", variableId: "me_2_key_3" },
			{ name: "ME2 KEY 4 on/off", variableId: "me_2_key_4" },
			{ name: "ME3 KEY 1 on/off", variableId: "me_3_key_1" },
			{ name: "ME3 KEY 2 on/off", variableId: "me_3_key_2" },
			{ name: "ME3 KEY 3 on/off", variableId: "me_3_key_3" },
			{ name: "ME3 KEY 4 on/off", variableId: "me_3_key_4" },
			{ name: "FLEX KEY 1 on/off", variableId: "flex_key_1" },
			{ name: "FLEX KEY 2 on/off", variableId: "flex_key_2" },
			{ name: "FLEX KEY 3 on/off", variableId: "flex_key_3" },
			{ name: "FLEX KEY 4 on/off", variableId: "flex_key_4" },
		],
		MES: [
			{ id: 1, label: "ME 1" },
			{ id: 2, label: "ME 2" },
			{ id: 3, label: "ME 3" },
		],
		MELS: [
			{ id: 1, label: "MELite 1" },
			{ id: 2, label: "MELite 2" },
			{ id: 3, label: "MELite 3" },
			{ id: 4, label: "MELite 4" },
			{ id: 5, label: "MELite 5" },
			{ id: 6, label: "MELite 6" },
		],
		KEYS: [
			{ id: "1,1", label: "ME1 Key1" },
			{ id: "1,2", label: "ME1 Key2" },
			{ id: "1,3", label: "ME1 Key3" },
			{ id: "1,4", label: "ME1 Key4" },
			{ id: "2,1", label: "ME2 Key1" },
			{ id: "2,2", label: "ME2 Key2" },
			{ id: "2,3", label: "ME2 Key3" },
			{ id: "2,4", label: "ME2 Key4" },
			{ id: "3,1", label: "ME3 Key1" },
			{ id: "3,2", label: "ME3 Key2" },
			{ id: "3,3", label: "ME3 Key3" },
			{ id: "3,4", label: "ME3 Key4" },
		],
		FLEX_KEYS: [
			{ id: 1, label: "Flex Key1" },
			{ id: 2, label: "Flex Key2" },
			{ id: 3, label: "Flex Key3" },
			{ id: 4, label: "Flex Key4" },
		],
		get SOURCES_ME() {
			let sources = [
				// Built-in Inputs
				{ id: 1, label: "Source 1", sName: "In 1" },
				{ id: 2, label: "Source 2", sName: "In 2" },
				{ id: 3, label: "Source 3", sName: "In 3" },
				{ id: 4, label: "Source 4", sName: "In 4" },
				{ id: 5, label: "Source 5", sName: "In 5" },
				{ id: 6, label: "Source 6", sName: "In 6" },
				{ id: 7, label: "Source 7", sName: "In 7" },
				{ id: 8, label: "Source 8", sName: "In 8" },
				{ id: 9, label: "Source 9", sName: "In 9" },
				{ id: 10, label: "Source 10", sName: "In10" },
				{ id: 11, label: "Source 11", sName: "In11" },
				{ id: 12, label: "Source 12", sName: "In12" },
				{ id: 13, label: "Source 13", sName: "In13" },
				{ id: 14, label: "Source 14", sName: "In14" },
				{ id: 15, label: "Source 15", sName: "In15" },
				{ id: 16, label: "Source 16", sName: "In16" },
				{ id: 17, label: "Source 17", sName: "In17" },
				{ id: 18, label: "Source 18", sName: "In18" },
				{ id: 19, label: "Source 19", sName: "In19" },
				{ id: 20, label: "Source 20", sName: "In20" },
				{ id: 21, label: "Source 21", sName: "In21" },
				{ id: 22, label: "Source 22", sName: "In22" },
				{ id: 23, label: "Source 23", sName: "In23" },
				{ id: 24, label: "Source 24", sName: "In24" },
				// Optional expansion card inputs
				{ id: 25, label: "Source 25", sName: "In25" },
				{ id: 26, label: "Source 26", sName: "In26" },
				{ id: 27, label: "Source 27", sName: "In27" },
				{ id: 28, label: "Source 28", sName: "In28" },
				{ id: 29, label: "Source 29", sName: "In29" },
				{ id: 30, label: "Source 30", sName: "In30" },
				{ id: 31, label: "Source 31", sName: "In31" },
				{ id: 32, label: "Source 32", sName: "In32" },
				{ id: 33, label: "Source 33", sName: "In33" },
				{ id: 34, label: "Source 34", sName: "In34" },
				{ id: 35, label: "Source 35", sName: "In35" },
				{ id: 36, label: "Source 36", sName: "In36" },
				{ id: 37, label: "Source 37", sName: "In37" },
				{ id: 38, label: "Source 38", sName: "In38" },
				{ id: 39, label: "Source 39", sName: "In39" },
				{ id: 40, label: "Source 40", sName: "In40" },
				{ id: 41, label: "Source 41", sName: "In41" },
				{ id: 42, label: "Source 42", sName: "In42" },
				{ id: 43, label: "Source 43", sName: "In43" },
				{ id: 44, label: "Source 44", sName: "In44" },
				{ id: 45, label: "Source 45", sName: "In45" },
				{ id: 46, label: "Source 46", sName: "In46" },
				{ id: 47, label: "Source 47", sName: "In47" },
				{ id: 48, label: "Source 48", sName: "In48" },
			];
			let system = [
				// System inputs
				{ id: 0, label: "Black", sName: "BLK " },
				{ id: 49, label: "Still 1", sName: "STL1" },
				{ id: 50, label: "Still 2", sName: "STL2" },
				{ id: 51, label: "Still 3", sName: "STL3" },
				{ id: 52, label: "Still 4", sName: "STL4" },
				{ id: 53, label: "Still 5", sName: "STL5" },
				{ id: 54, label: "Still 6", sName: "STL6" },
				{ id: 61, label: "Color Bars", sName: "BARS" },
				{ id: 62, label: "White", sName: "WHT " },
				{ id: 63, label: "Matte 1", sName: "MAT1" },
				{ id: 64, label: "Matte 2", sName: "MAT2" },
				{ id: 65, label: "Grand Matte", sName: "GMAT" },

				{ id: 72, label: "ME1", sName: "ME1 " },
				{ id: 73, label: "ME1 Out 1", sName: "M1O1" },
				{ id: 74, label: "ME1 Out 2", sName: "M1O2" },
				{ id: 75, label: "ME2", sName: "ME2 " },
				{ id: 76, label: "ME2 Out 1", sName: "M2O1" },
				{ id: 77, label: "ME2 Out 2", sName: "M2O2" },

				{ id: 80, label: "MV1 Out A", sName: "MV1A" },
				{ id: 81, label: "MV2 Out A", sName: "MV2A" },

				{ id: 84, label: "ME3", sName: "ME3 " },
				{ id: 85, label: "ME3 Out 1", sName: "M3O1" },
				{ id: 86, label: "ME3 Out 2", sName: "M3O2" },

				{ id: 95, label: "MV3 Out A", sName: "MV3A" },
				{ id: 96, label: "MV4 Out A", sName: "MV4A" },

				{ id: 105, label: "ME1 Out 3", sName: "M1O3" },
				{ id: 106, label: "ME2 Out 3", sName: "M2O3" },
				{ id: 107, label: "ME3 Out 3", sName: "M3O3" },
				{ id: 108, label: "Chroma Key 1 Fill", sName: "CK1F" },
				{ id: 109, label: "Chroma Key 1 Key", sName: "CK1K" },
				{ id: 110, label: "Chroma Key 2 Fill", sName: "CK2F" },
				{ id: 111, label: "Chroma Key 2 Key", sName: "CK2K" },
				{ id: 112, label: "Chroma Key 3 Fill", sName: "CK3F" },
				{ id: 113, label: "Chroma Key 3 Key", sName: "CK3K" },
				{ id: 114, label: "Chroma Key 4 Fill", sName: "CK4F" },
				{ id: 115, label: "Chroma Key 4 Key", sName: "CK4K" },
				{ id: 116, label: "Chroma Key 5 Fill", sName: "CK5F" },
				{ id: 117, label: "Chroma Key 5 Key", sName: "CK5K" },
				{ id: 118, label: "Chroma Key 6 Fill", sName: "CK6F" },
				{ id: 119, label: "Chroma Key 6 Key", sName: "CK6K" },
				{ id: 120, label: "Chroma Key 7 Fill", sName: "CK7F" },
				{ id: 121, label: "Chroma Key 7 Key", sName: "CK7K" },
				{ id: 122, label: "Chroma Key 8 Fill", sName: "CK8F" },
				{ id: 123, label: "Chroma Key 8 Key", sName: "CK8K" },
				{ id: 124, label: "Effect 1", sName: "EFF1" },
				{ id: 125, label: "Effect 2", sName: "EFF2" },
				{ id: 126, label: "Effect 3", sName: "EFF3" },
				{ id: 127, label: "Effect 4", sName: "EFF4" },

				{ id: 130, label: "Color Correct 1", sName: "CC 1" },
				{ id: 131, label: "Color Correct 2", sName: "CC 2" },
				{ id: 132, label: "Color Correct 3", sName: "CC 3" },
				{ id: 133, label: "Color Correct 4", sName: "CC 4" },
				{ id: 134, label: "Color Correct 5", sName: "CC 5" },
				{ id: 135, label: "Color Correct 6", sName: "CC 6" },
				{ id: 136, label: "Color Correct 7", sName: "CC 7" },
				{ id: 137, label: "Color Correct 8", sName: "CC 8" },

				{ id: 139, label: "Aux 1", sName: "Aux1" },
				{ id: 140, label: "Aux 2", sName: "Aux2" },
				{ id: 141, label: "Aux 3", sName: "Aux3" },
				{ id: 142, label: "Aux 4", sName: "Aux4" },
				{ id: 143, label: "Aux 5", sName: "Aux5" },
				{ id: 144, label: "Aux 6", sName: "Aux6" },
				{ id: 145, label: "Aux 7", sName: "Aux7" },
				{ id: 146, label: "Aux 8", sName: "Aux8" },
				{ id: 147, label: "Aux 9", sName: "Aux9" },
				{ id: 148, label: "Aux 10", sName: "Ax10" },
				{ id: 149, label: "Aux 11", sName: "Ax11" },
				{ id: 150, label: "Aux 12", sName: "Ax12" },
				{ id: 151, label: "Aux 13", sName: "Ax13" },
				{ id: 152, label: "Aux 14", sName: "Ax14" },
				{ id: 153, label: "Aux 15", sName: "Ax15" },
				{ id: 154, label: "Aux 16", sName: "Ax16" },
				{ id: 155, label: "Aux 17", sName: "Ax17" },
				{ id: 156, label: "Aux 18", sName: "Ax18" },
				{ id: 157, label: "MELite 1 PGM", sName: "ML1P" },
				{ id: 158, label: "MELite 2 PGM", sName: "ML2P" },
				{ id: 159, label: "MELite 3 PGM", sName: "ML3P" },
				{ id: 160, label: "MELite 4 PGM", sName: "ML4P" },
				{ id: 161, label: "MELite 5 PGM", sName: "ML5P" },
				{ id: 162, label: "MELite 6 PGM", sName: "ML6P" },
				{ id: 163, label: "MELite 1 PVW", sName: "ML1V" },
				{ id: 164, label: "MELite 2 PVW", sName: "ML2V" },
				{ id: 165, label: "MELite 3 PVW", sName: "ML3V" },
				{ id: 166, label: "MELite 4 PVW", sName: "ML4V" },
				{ id: 167, label: "MELite 5 PVW", sName: "ML5V" },
				{ id: 168, label: "MELite 6 PVW", sName: "ML6V" },
				{ id: 169, label: "Still 1 Key", sName: "STK1" },
				{ id: 170, label: "Still 2 Key", sName: "STK2" },
				{ id: 171, label: "Still 3 Key", sName: "STK3" },
				{ id: 172, label: "Still 4 Key", sName: "STK4" },
				{ id: 173, label: "Still 5 Key", sName: "STK5" },
				{ id: 174, label: "Still 6 Key", sName: "STK6" },
				{ id: 175, label: "MV1 Out B", sName: "MV1B" },
				{ id: 176, label: "MV2 Out B", sName: "MV2B" },
				{ id: 177, label: "MV3 Out B", sName: "MV3B" },
				{ id: 178, label: "MV4 Out B", sName: "MV4B" },
			];
			return sources.concat(
				system.sort((a, b) => (a.label > b.label ? 1 : -1)),
			);
		},
		get SOURCES_AUX() {
			return this.SOURCES_ME; // HVS2000 Has no Aux-only sources
		},
	},
};
